#!/usr/bin/env python3
"""
codebase_narrative.py — Add a semantic narrative section to codebase briefs.

Reads the structural brief generated by codebase_indexer.py, feeds it along with
a few key context files to a local Ollama model, and appends (or replaces) the
narrative section in the brief file.

Gated on Ollama availability — exits 0 (non-fatal) if unreachable or model absent.
Idempotent: re-running replaces the existing ## Narrative section.

Usage:
  python3 tools/codebase_narrative.py [project_dir] [--model MODEL] [--dry-run]
  python3 tools/codebase_narrative.py --all [--model MODEL]

  project_dir   Project root (default: current directory)
  --model       Ollama model to use (default: llama3.2 or first available)
  --all         Regenerate briefs for all projects in project registry
  --dry-run     Show what would be generated without writing
  --force       Regenerate even if narrative section is already present
"""

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent.parent

OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://localhost:11434")
DEFAULT_MODELS = ["llama3.2", "llama3.1", "llama3", "mistral", "qwen2.5:3b"]
NARRATIVE_MARKER = "## Narrative"
NARRATIVE_TOKEN_TARGET = 400

# Key files to include as context alongside the structural brief
KEY_CONTEXT_FILES = [
    "prompts/goal.txt",
    "README.md",
    "CLAUDE.md",
]


def check_ollama(model=None):
    """Return (available: bool, model_to_use: str|None)."""
    try:
        req = urllib.request.Request(f"{OLLAMA_URL}/api/tags")
        with urllib.request.urlopen(req, timeout=3) as resp:
            data = json.loads(resp.read())
        available_models = [m["name"].split(":")[0] for m in data.get("models", [])]
        if not available_models:
            print("codebase_narrative: Ollama reachable but no models installed.", file=sys.stderr)
            return False, None
        if model:
            if model.split(":")[0] in available_models:
                return True, model
            print(f"codebase_narrative: model '{model}' not found. Available: {available_models}", file=sys.stderr)
            return False, None
        # Pick first available from preferred list
        for m in DEFAULT_MODELS:
            if m in available_models:
                return True, m
        # Fall back to whatever is first
        return True, data["models"][0]["name"]
    except (urllib.error.URLError, OSError, json.JSONDecodeError, KeyError):
        print(f"codebase_narrative: Ollama not reachable at {OLLAMA_URL} — skipping.", file=sys.stderr)
        return False, None


def call_ollama(model, prompt, max_tokens=600):
    """Call Ollama generate API, return response text."""
    payload = json.dumps({
        "model": model,
        "prompt": prompt,
        "stream": False,
        "options": {"num_predict": max_tokens, "temperature": 0.3},
    }).encode()
    req = urllib.request.Request(
        f"{OLLAMA_URL}/api/generate",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        result = json.loads(resp.read())
    return result.get("response", "").strip()


def read_context_files(project_root):
    """Read KEY_CONTEXT_FILES that exist; return as a dict path->content."""
    ctx = {}
    for rel in KEY_CONTEXT_FILES:
        p = project_root / rel
        if p.exists():
            try:
                text = p.read_text(encoding="utf-8", errors="replace")
                ctx[rel] = text[:1200]  # cap to avoid blowing up the prompt
            except OSError:
                pass
    return ctx


def build_prompt(project_name, structural_brief, context_files):
    """Build the Ollama prompt for narrative generation."""
    ctx_section = ""
    if context_files:
        ctx_section = "\n\n### Key context files:\n"
        for path, content in context_files.items():
            ctx_section += f"\n--- {path} ---\n{content}\n"

    return f"""You are analyzing a software project called "{project_name}".
Below is a structural map of the project (auto-generated from its files) and a few key context files.

Write a concise narrative (~{NARRATIVE_TOKEN_TARGET} tokens) that explains:
1. What this project does and its core purpose
2. How it is structured at a high level (key layers, main components)
3. What a new engineer needs to understand to work on it effectively

Be specific. Avoid generic descriptions. Use the actual file names and components from the structural map.
Do not use markdown headers. Write in plain paragraphs.

### Structural map:
{structural_brief}
{ctx_section}
Narrative:"""


def read_brief(brief_path):
    """Read brief, return (pre_narrative: str, has_existing_narrative: bool)."""
    if not brief_path.exists():
        return "", False
    text = brief_path.read_text(encoding="utf-8", errors="replace")
    if NARRATIVE_MARKER in text:
        pre = text[:text.index(NARRATIVE_MARKER)].rstrip()
        return pre, True
    return text.rstrip(), False


def write_brief_with_narrative(brief_path, pre_narrative, narrative, model):
    """Overwrite the brief with the structural section + new narrative."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    content = f"{pre_narrative}\n\n{NARRATIVE_MARKER}\n_Generated {now} via Ollama ({model})_\n\n{narrative}\n"
    brief_path.write_text(content, encoding="utf-8")


def process_project(project_root, model, dry_run=False, force=False):
    """Generate/update narrative for a single project. Returns True on success."""
    project_root = Path(project_root).resolve()
    project_name = project_root.name

    briefs_dir = PROJECT_DIR / "memory" / "codebase_briefs"
    brief_path = briefs_dir / f"{project_name}.md"

    if not brief_path.exists():
        print(f"codebase_narrative: no brief found for '{project_name}' at {brief_path}", file=sys.stderr)
        print(f"  Run: python3 tools/codebase_indexer.py {project_root}", file=sys.stderr)
        return False

    pre_narrative, has_existing = read_brief(brief_path)

    if has_existing and not force:
        print(f"codebase_narrative: '{project_name}' already has narrative (use --force to regenerate)")
        return True

    context_files = read_context_files(project_root)
    prompt = build_prompt(project_name, pre_narrative, context_files)

    if dry_run:
        print(f"=== DRY RUN: {project_name} ===")
        print(f"Brief: {brief_path}")
        print(f"Context files found: {list(context_files.keys())}")
        print(f"Prompt ({len(prompt)} chars):")
        print(prompt[:500] + "..." if len(prompt) > 500 else prompt)
        return True

    print(f"codebase_narrative: generating narrative for '{project_name}' using {model}...")
    narrative = call_ollama(model, prompt)

    if not narrative:
        print(f"codebase_narrative: empty response from Ollama for '{project_name}'", file=sys.stderr)
        return False

    write_brief_with_narrative(brief_path, pre_narrative, narrative, model)
    print(f"codebase_narrative: wrote narrative to {brief_path} ({len(narrative)} chars)")
    return True


def get_all_project_dirs():
    """Return list of project root paths from project registry if available."""
    registry_path = PROJECT_DIR / "config" / "project_registry.json"
    if registry_path.exists():
        try:
            data = json.loads(registry_path.read_text())
            dirs = []
            for entry in data.values() if isinstance(data, dict) else data:
                d = entry.get("directory")
                if d and Path(d).is_dir():
                    dirs.append(d)
            if dirs:
                return dirs
        except (json.JSONDecodeError, KeyError, TypeError):
            pass
    # Fall back to briefs that already exist
    briefs_dir = PROJECT_DIR / "memory" / "codebase_briefs"
    if briefs_dir.exists():
        return [str(PROJECT_DIR.parent / p.stem) for p in briefs_dir.glob("*.md")
                if (PROJECT_DIR.parent / p.stem).is_dir()]
    return [str(PROJECT_DIR)]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project_dir", nargs="?", default=str(PROJECT_DIR),
                        help="Project root directory")
    parser.add_argument("--model", default=None, help="Ollama model to use")
    parser.add_argument("--all", action="store_true", dest="all_projects",
                        help="Regenerate for all known projects")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--force", action="store_true",
                        help="Replace existing narrative section")
    args = parser.parse_args()

    available, model = check_ollama(args.model)
    if not available:
        sys.exit(0)  # non-fatal — caller treats exit 0 as skip

    project_dirs = get_all_project_dirs() if args.all_projects else [args.project_dir]

    success_count = 0
    for d in project_dirs:
        if process_project(d, model, dry_run=args.dry_run, force=args.force):
            success_count += 1

    print(f"codebase_narrative: done ({success_count}/{len(project_dirs)} projects)")


if __name__ == "__main__":
    main()
